[#ftl]
[@b.head/]
[@b.toolbar title="授课计划修改"]
  bar.addBack();
[/@]
[#assign course=teachingPlan.clazz.course/]
  [@b.form theme="list" action=b.rest.save(teachingPlan) name="teachingPlanForm"]
    [@b.field label="课程"]${course.code} ${course.name} ${course.defaultCredits!}学分[/@]
    [@b.select name="teachingPlan.office.id" label="教研室" items=offices value=teachingPlan.office! option="id,name" empty="..." /]
    [@b.formfoot]
      [@b.submit value="保存" /]
    [/@]
  [/@]
[@b.foot/]
