[#ftl]
[@b.head/]
[@b.toolbar title="课程资料维护"]bar.addBack();[/@]
    [@b.form action=sa theme="list" action=b.rest.save(course)]
      [@b.field label="课程"]${course.code} ${course.name} ${course.defaultCredits}学分[/@]
      [@b.field label="课程类别"]${(course.courseType.name)!'--'}[/@]
      [@b.field label="开课院系"]${(course.department.name)!'--'}[/@]
      [@b.textarea label="课程简介" name="profile.description" value=profile.description cols="80" rows="10" required="true" maxlength="500" comment="500字以内" placeholder="简述课程的目标、主要内容、获得的荣誉称号"/]
      [@b.textarea label="英文简介" name="profile.enDescription" value=profile.enDescription!  cols="80" rows="10" maxlength="500" comment="500字以内"/]
      [@b.field label="已有大纲"]
        [#if syllabuses?size>0]
        [#list syllabuses as s]
          ${s.semester.schoolYear}学年${s.semester.name}学期 ${s.writer.name} 更新于${s.updatedAt?string("yyyy-MM-dd HH:mm")} [@b.a href="!attachment?doc.id="+s.id target="_blank"]下载[/@]
        [/#list]
        [#else]尚无[/#if]
      [/@]
      [@b.select label="课程大纲作者" name="syllabusDoc.writer.id" href=Ems.api+"/base/users.json?isTeacher=true&pageSize=10000" option="id,name+' '+data.department.name"  comment="请上传已经审核通过的附件，并选择作者"/]
      [@b.file label="更新大纲" name="attachment" extensions="doc,docx,pdf" maxSize="10M"/]
      [@b.formfoot]
        &nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
    [/@]
[@b.foot/]
