[@b.head/]
<div class="container-fluid">
  [@b.toolbar title="我的授课教案"]
  [/@]
  [@base.semester_bar value=semester! formName='courseTableForm'/]
  <div class="search-container">
    <div class="search-list">
    [@b.grid items=clazzes var="clazz"]
      [@b.row]
        [@b.col width="4%" title="序号"]${clazz_index+1}[/@]
        [@b.col width="6%" title="课程序号"]${(clazz.crn)?if_exists}[/@]
        [@b.col width="9%" title="课程代码"]${(clazz.course.code)?if_exists}[/@]
        [@b.col title="课程名称"]${(clazz.course.name)?if_exists}[/@]
        [@b.col width="15%" title="课程类型"]${(clazz.courseType.name)?if_exists}[/@]
        [@b.col width="4%" title="学分"]${clazz.course.defaultCredits}[/@]
        [@b.col width="5%" title="总学时"]${(clazz.course.creditHours)?if_exists}[/@]
        [@b.col width="5%" title="学生数"]${clazz.enrollment.courseTakers?size}[/@]
        [@b.col width="10%" title="任课教师"][#list clazz.teachers as t]${t.name}[#sep] [/#list][/@]
        [@b.col width="18%" title="操作"]
          [#if plans.get(clazz)??]
            [#if programs.get(clazz)??]
              [#assign program = programs.get(clazz)/]
              [@b.a href="!info?clazz.id="+clazz.id+"&program.id="+program.id target="_blank"]查看<span class="text-muted">(${program.writer.name})</span>[/@]
              [@b.a href="!edit?clazz.id="+clazz.id target="_blank"]修改[/@]
            [#elseif coursePrograms.get(clazz.course)??]
              [#assign program = coursePrograms.get(clazz.course)/]
              [@b.a href="!info?clazz.id="+clazz.id+"&program.id="+program.id target="_blank"]查看<span class="text-muted">(${program.writer.name})</span>[/@]
              [@b.a href="!edit?clazz.id="+clazz.id target="_blank" onclick="if(confirm('已经存在同一课程的教案，是否继续添加？')){return true;}else{return false;}"]添加[/@]
            [#else]
              [@b.a href="!edit?clazz.id="+clazz.id target="_blank" ]添加[/@]
            [/#if]

            [#--[#if programs.get(clazz)??]
              [@b.a href="!report?plan.id="+plans.get(clazz).id target="_blank"]预览[/@]
              [@b.a href="!pdf?plan.id="+plans.get(clazz).id target="_blank"]下载PDF[/@]
            [/#if]
            --]
          [#else]
            授课计划缺失，请先修订授课计划
          [/#if]
        [/@]
      [/@]
    [/@]
    </div>
  </div>
</div>
[@b.foot/]
