[#ftl]
[@b.head/]
[@b.toolbar title="课程资料维护"]bar.addBack();[/@]
    [@b.form action=sa theme="list" action=b.rest.save(course)]
      [@b.field label="课程"]${course.code} ${course.name} ${course.credits}学分[/@]
      [@b.field label="课程类别"]${(course.courseType.name)!'--'}[/@]
      [@b.field label="开课院系"]${(course.department.name)!'--'}[/@]
      [@b.textarea label="课程简介" name="profile.description" value=profile.description cols="80" rows="10" required="true" maxlength="500" comment="500字以内" placeholder="简述课程的目标、主要内容、获得的荣誉称号"/]
      [@b.textarea label="英文简介" name="profile.enDescription" value=profile.enDescription!  cols="80" rows="10" maxlength="500" comment="500字以内"/]
      [@b.field label="最新大纲"]
        [#if syllabuses?size>0]
        [#list syllabuses as s]
          ${s.semester.schoolYear}学年${s.semester.name}学期 ${s.author.name} 更新于${s.updatedAt?string("yyyy-MM-dd HH:mm")} [#list s.attachments as a][@b.a href="!attachment?file.id="+a.id target="_blank"]下载[/@][/#list]
        [/#list]
        [#else]尚无[/#if]
      [/@]
      [@b.select label="课程大纲作者" name="syllabus.author.id" href=Ems.api+"/base/users.json?isTeacher=true&pageSize=10000" option="id,name+' '+data.department.name"  comment="请上传已经审核通过的附件，并选择作者"/]
      [@b.file label="大纲附件" name="attachment"/]
      [@b.formfoot]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
    [/@]
[@b.foot/]
