[#ftl]
[@b.head/]
[@b.toolbar title="修改课程负责人"]bar.addBack();[/@]
  [@b.form action=b.rest.save(courseTask) theme="list"]
    [@b.field label="学年学期"]${courseTask.semester.schoolYear}学年${courseTask.semester.name}学期[/@]
    [@b.field label="课程"]${courseTask.course.name}(${courseTask.course.code})[/@]
    [@b.field label="开课学院"]${courseTask.department.name}[/@]
    [@b.select style="width:100px" name="courseTask.office.id" label="教研室" items=offices option="id,name" empty="..." /]
    [@b.field label="任课教师"]
      [#list courseTask.teachers?sort_by("name")  as teacher]${teacher.name}[#if teacher_has_next]&nbsp;[/#if][/#list]
    [/@]
    [@b.select name="courseTask.director.id" label="负责人" value=courseTask.director! items=directors?sort_by("name")  option="id,description" required="true"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
  [#list 1..20 as i]<br>[/#list]
[@b.foot/]
