[#ftl]
[@b.head/]
[@b.toolbar title="修改课程负责人"]bar.addBack();[/@]
  [@b.form action=b.rest.save(courseTask) theme="list"]
    [@b.field label="学年学期"]${courseTask.semester.schoolYear}学年${courseTask.semester.name}学期[/@]
    [@b.field label="课程"]${courseTask.course.name}(${courseTask.course.code})[/@]
    [@b.field label="开课学院"]${courseTask.department.name}[/@]
    [@b.number label="顺序号" name="courseTask.idx" value=courseTask.idx required="true"/]
    [@b.select style="width:100px" name="courseTask.office.id" label="教研室" items=offices value=courseTask.office! option="id,name" empty="..." /]
    [@b.field label="任课教师"]
      [#list courseTask.teachers?sort_by("name") as teacher]${teacher.name}[#if teacher_has_next]&nbsp;[/#if][/#list]
    [/@]
    [@b.select name="courseTask.director.id" label="负责人" value=courseTask.director! items=directors?sort_by("name")  option="id,description" required="true"/]
    [@b.radios label="是否需要大纲"  name="courseTask.syllabusRequired" value=courseTask.syllabusRequired items="1:common.yes,0:common.no" required="true"/]
    [@b.radios label="是否设置实验"  name="courseTask.hasExperiment" value=courseTask.hasExperiment!false items="1:common.yes,0:common.no" required="true"/]
    [@b.number label="课外学时" name="courseTask.extraHours" value=courseTask.extraHours! /]
    [@b.radios name="courseTask.confirmed" items={'1':'确认','0':'可以根据排课信息自动更新'} label="是否确认" value=courseTask.confirmed/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
  [#list 1..20 as i]<br>[/#list]
[@b.foot/]
